// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/animals/data/objectbox/animal_dto.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3144368555543600586),
    name: 'AnimalDto',
    lastPropertyId: const obx_int.IdUid(8, 5147354743626250393),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5265129337428283863),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2474286250018129873),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 5490562747739727627),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6523485680306826346),
        name: 'type',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 4301130392780657170),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3601708536084916764),
        name: 'sex',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6687449509024339706),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7270497296543028818),
        name: 'habitat',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7512759831358541390),
        name: 'factsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5147354743626250393),
        name: 'imageUrl',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 3144368555543600586),
    lastIndexId: const obx_int.IdUid(2, 4301130392780657170),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AnimalDto: obx_int.EntityDefinition<AnimalDto>(
      model: _entities[0],
      toOneRelations: (AnimalDto object) => [],
      toManyRelations: (AnimalDto object) => {},
      getId: (AnimalDto object) => object.id,
      setId: (AnimalDto object, int id) {
        object.id = id;
      },
      objectToFB: (AnimalDto object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final typeOffset = fbb.writeString(object.type);
        final sexOffset = fbb.writeString(object.sex);
        final descriptionOffset = fbb.writeString(object.description);
        final habitatOffset = fbb.writeString(object.habitat);
        final factsJsonOffset = fbb.writeString(object.factsJson);
        final imageUrlOffset = fbb.writeString(object.imageUrl);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, typeOffset);
        fbb.addOffset(3, sexOffset);
        fbb.addOffset(4, descriptionOffset);
        fbb.addOffset(5, habitatOffset);
        fbb.addOffset(6, factsJsonOffset);
        fbb.addOffset(7, imageUrlOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final sexParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final habitatParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final factsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final imageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final object = AnimalDto(
          id: idParam,
          name: nameParam,
          type: typeParam,
          sex: sexParam,
          description: descriptionParam,
          habitat: habitatParam,
          factsJson: factsJsonParam,
          imageUrl: imageUrlParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AnimalDto] entity fields to define ObjectBox queries.
class AnimalDto_ {
  /// See [AnimalDto.id].
  static final id = obx.QueryIntegerProperty<AnimalDto>(
    _entities[0].properties[0],
  );

  /// See [AnimalDto.name].
  static final name = obx.QueryStringProperty<AnimalDto>(
    _entities[0].properties[1],
  );

  /// See [AnimalDto.type].
  static final type = obx.QueryStringProperty<AnimalDto>(
    _entities[0].properties[2],
  );

  /// See [AnimalDto.sex].
  static final sex = obx.QueryStringProperty<AnimalDto>(
    _entities[0].properties[3],
  );

  /// See [AnimalDto.description].
  static final description = obx.QueryStringProperty<AnimalDto>(
    _entities[0].properties[4],
  );

  /// See [AnimalDto.habitat].
  static final habitat = obx.QueryStringProperty<AnimalDto>(
    _entities[0].properties[5],
  );

  /// See [AnimalDto.factsJson].
  static final factsJson = obx.QueryStringProperty<AnimalDto>(
    _entities[0].properties[6],
  );

  /// See [AnimalDto.imageUrl].
  static final imageUrl = obx.QueryStringProperty<AnimalDto>(
    _entities[0].properties[7],
  );
}
